baseURL: 'https://primetzvan.github.io/hugo-project/'
#baseURL: 'http://example.org/'
languageCode: 'de-DE'
title: 'Leodatabaselearner'
theme: easytheme
menu:
  main:
    - name: Installation
      url: /docs/installation
      weight: 2
    - name: Project Infos
      url: /docs/backgroundInfo
      weight: 2
    - name: Sprints
      url: /docs/sprints
      weight: 1
    - name: About
      url: /docs/about
      weight: 1
  refpa:
    - name: Start
      url: /
      weight: 3
    - name: Installation
      url: /docs/installation
      weight: 2
    - name: Project Infos
      url: /docs/backgroundInfo
      weight: 2
    - name: Sprints
      url: /docs/sprints
      weight: 1
    - name: About
      url: /docs/about
      weight: 1
  footer:
    - name: About
      url: /docs/about
      weight: 1
  button:
    - name: Read More
      url: /docs/backgroundInfo
      weight: 1
